// <auto-generated />
using ApiP.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiP.Migrations
{
    [DbContext(typeof(TiendaPeliculasContext))]
    partial class TiendaPeliculasContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApiP.Models.Pelicula", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Año")
                        .HasColumnType("int");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Peliculas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Año = 1997,
                            Director = "James Cameron",
                            Titulo = "Titanic"
                        },
                        new
                        {
                            Id = 2,
                            Año = 1994,
                            Director = "Frank Darabont",
                            Titulo = "The Shawshank Redemption"
                        },
                        new
                        {
                            Id = 3,
                            Año = 1972,
                            Director = "Francis Ford Coppola",
                            Titulo = "The Godfather"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
